### ISSUE TITLE
Problem with parts of the dpgp outfile

### ISSUE THREAD

**Issue by rtraborn** [rtraborn/Dm_Promoter_PopGen#13]
Hi all: today I noticed that the last ~1200 lines of dpgp.csv are empty. 
Could you look into this when have the chance @wylht?

**Comment by kbathina** [comment]
hmm... that is strange. 
Adding the shape values worked for all of the other datasets. Do you know if there something different with that dataset?

**Comment by rtraborn** [comment]
I don't- I just did 
 `less dpgp.csv `
and saw that a number of lines were empty. Maybe there's a nomenclature issue for one of the chromosomes?

**Comment by kbathina** [comment]
I'll try to see whats happening. I have an exam tonight so i'll work on it afterwards.

**Comment by rtraborn** [comment]
Great- thanks!

**Comment by wylht** [comment]
Oh, github redirect emails to my another mailbox I used to register github.

 

That is because dpgp3 contains corrupted data. After removing them, now it should be fine. 

 

So h_adjacent_tss_dpgp3 is a god file. But I didn’t update all_h_dpgp3.csv yesterday because I thought it is contained in the new h_adjacent_tss_dpgp3

 

If you need it, I will update all_h_dpgp3 in a few minutes. 

 

Best,

 

Xuan

**Comment by kbathina** [comment]
So is the all_h_dpgp3_sequences.csv file fixed? I can download it and add the shape indexes when ready.

**Comment by wylht** [comment]
No, it is not fixed. 

 

It is my fault that when I generate the new csv files with TSS columns, I forget to save the original script. For I thought the new csv files contains all information in old version csv files. 

 

I need several minutes to revert the changes and create a script to generate that file. 

If you find modify your script faster (just need to change the column number), it can work too. 

 

a.       Columns are:

chr, tss start, tss end, direction of strand, start of major tss, end of major tss, 501 columns of h values; h values for TSS

 

Best,

 

Xuan

**Comment by rtraborn** [comment]
I’m not sure- Xuan can fill us in.

Taylor

On Dec 14, 2016, at 1:12 PM, Krishna Bathina <notifications@github.com<mailto:notifications@github.com>> wrote:


So is the all_h_dpgp3_sequences.csv file fixed? I can download it and add the shape indexes when ready.

**Comment by wylht** [comment]
OK, I found it need time to create a new script. 

So I just cropped the new h_adjacent_tss_dpgp3 to get “all_h_dpgp3”

 

Now it is fixed. 

 

Best,

 

Xuan

 

From: 王玄 [mailto:wylht@foxmail.com] 
Sent: Wednesday, December 14, 2016 2:08 PM
To: 'rtraborn/Dm_Promoter_PopGen' <reply@reply.github.com>; 'rtraborn/Dm_Promoter_PopGen' <Dm_Promoter_PopGen@noreply.github.com>
Cc: 'Assign' <assign@noreply.github.com>
Subject: RE: [rtraborn/Dm_Promoter_PopGen] Problem with parts of the dpgp outfile (#13)

 

No, it is not fixed. 

 

It is my fault that when I generate the new csv files with TSS columns, I forget to save the original script. For I thought the new csv files contains all information in old version csv files. 

 

I need several minutes to revert the changes and create a script to generate that file. 

If you find modify your script faster (just need to change the column number), it can work too. 

 

a.       Columns are:

chr, tss start, tss end, direction of strand, start of major tss, end of major tss, 501 columns of h values; h values for TSS

 

Best,

 

Xuan

**Comment by rtraborn** [comment]
Thanks Xuan!

Taylor

On Dec 14, 2016, at 2:21 PM, wylht <notifications@github.com<mailto:notifications@github.com>> wrote:

OK, I found it need time to create a new script.

So I just cropped the new h_adjacent_tss_dpgp3 to get “all_h_dpgp3”



Now it is fixed.



Best,



Xuan



From: 王玄 [mailto:wylht@foxmail.com]
Sent: Wednesday, December 14, 2016 2:08 PM
To: 'rtraborn/Dm_Promoter_PopGen' <reply@reply.github.com<mailto:reply@reply.github.com>>; 'rtraborn/Dm_Promoter_PopGen' <Dm_Promoter_PopGen@noreply.github.com<mailto:Dm_Promoter_PopGen@noreply.github.com>>
Cc: 'Assign' <assign@noreply.github.com<mailto:assign@noreply.github.com>>
Subject: RE: [rtraborn/Dm_Promoter_PopGen] Problem with parts of the dpgp outfile (#13)



No, it is not fixed.



It is my fault that when I generate the new csv files with TSS columns, I forget to save the original script. For I thought the new csv files contains all information in old version csv files.



I need several minutes to revert the changes and create a script to generate that file.

If you find modify your script faster (just need to change the column number), it can work too.



a. Columns are:

chr, tss start, tss end, direction of strand, start of major tss, end of major tss, 501 columns of h values; h values for TSS



Best,



Xuan

**Comment by rtraborn** [comment]
@wylht- is this file located in our /N/dc2/projects directory?

**Comment by kbathina** [comment]
It is located in /N/dc2/projects/PromoterPopGen/test. I added the shape values to the dpgp data and submitted a pull request.

**Comment by rtraborn** [comment]
@kbathina thanks! I just went ahead with the merge. (Also thanks to you @wylht)
