### ISSUE TITLE
Test pi.py

### ISSUE THREAD

**Issue by rtraborn** [rtraborn/Dm_Promoter_PopGen#5]
Taylor to do this once sample (toy) data is available.

**Comment by kbathina** [comment]
I tested the code with sample sequences I made up and it worked. Of course, some real data would be better.

**Comment by rtraborn** [comment]
Cool. Can you add your test sequences to the repo?

**Comment by kbathina** [comment]
I used four random strings as sequences. The strings are located in the first couple of lines of code. Currently, they are commented out.

**Comment by rtraborn** [comment]
I see those. Can you add a (commented out) sample command in the script itself or in a README when you have the chance?

**Comment by rtraborn** [comment]
I updated the pi.py script to return the test data that @kbathina embedded in the script. 
Now we need to convert this to a function, and either add a separate function to import seq data or include that ability inside the existing function. Closing issue.
